[project]
name = "vietnamese-minimal-pairs-anki-card-creator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-cloud-texttospeech>=2.33.0",
    "tqdm>=4.67.1",
]
